commonLabels:
  app.kubernetes.io/managed-by: vkpr
# -----------------------------------------------------------------------------
# alertmanager sub-chart parameters
# -----------------------------------------------------------------------------
alertmanager:
  enabled: false
  ingress:
    enabled: false
    ingressClassName: nginx
    hosts:
      - paths: "/"
    pathType: ImplementationSpecific
# -----------------------------------------------------------------------------
# grafana sub-chart parameters
# -----------------------------------------------------------------------------
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    path: "/"
# -----------------------------------------------------------------------------
# prometheus sub-chart parameters
# -----------------------------------------------------------------------------
prometheusOperator:
  enabled: true
prometheus:
  enabled: true
