apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-stack-kube-prom-prometheus.vkpr:9090
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 10s
    - access: proxy
      basicAuth: false
      editable: true
      isDefault: false
      name: Loki
      type: loki
      uid: loki
      url: http://loki.vkpr:3100
      version: 1
    - name: Jaeger
      type: jaeger
      uid: jaeger
      access: http
      url: http://jaeger-query.vkpr:16686
      isDefault: false
      version: 1
      editable: true
      basicAuth: false
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-stack
    meta.helm.sh/release-namespace: vkpr
  creationTimestamp: "2023-09-25T15:50:01Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.20.0
    chart: kube-prometheus-stack-45.20.0
    grafana_datasource: "1"
    heritage: Helm
    release: prometheus-stack
  name: prometheus-stack-kube-prom-grafana-datasource
  namespace: vkpr

