name: bats-testes

on:
  workflow_dispatch:

jobs:
  Igress_testes:
    runs-on: ubuntu-latest
    steps:

     - name: Install Vkpr
       run: |
          curl -fsSL https://get.vkpr.net/ | CONTROL_SKIP="true" bash
          alias vkpr="rit vkpr"

     - uses: actions/checkout@v3
     - name: bats-teste-kong-standard
       continue-on-error: true
       run: |
        ~/.vkpr/bats/bin/bats vkpr-test/kong/kong-standard.bats

     - name: bats-teste-kong-dbless
       continue-on-error: true
       run: |
        ~/.vkpr/bats/bin/bats vkpr-test/kong/kong-dbless.bats

     - name: bats-teste-nginx
       continue-on-error: true
       run: |
        ~/.vkpr/bats/bin/bats vkpr-test/nginx/nginx.bats
      
     - name: bats-teste-postgres
       continue-on-error: true
       run: |
        ~/.vkpr/bats/bin/bats vkpr-test/postgres/postgres.bats